module.exports = {
  BCRYPT_SALT_ROUNDS: parseInt(process.env.BCRYPT_SALT_ROUNDS) || 12,
  JWT_EXPIRY: process.env.JWT_EXPIRY || '15m',
  JWT_REFRESH_EXPIRY: process.env.JWT_REFRESH_EXPIRY || '7d',
  RATE_LIMIT_WINDOW_MS: parseInt(process.env.RATE_LIMIT_WINDOW_MS) || 900000,
  RATE_LIMIT_MAX_REQUESTS: parseInt(process.env.RATE_LIMIT_MAX_REQUESTS) || 100,
  ROOM_ACCESS_TOKEN_EXPIRY: parseInt(process.env.ROOM_ACCESS_TOKEN_EXPIRY) || 3600,
  MESSAGE_RATE_LIMIT: 10,
  ROOM_CREATION_LIMIT: 5,
  LOGIN_ATTEMPT_LIMIT: 5,
  ADMIN_LOGIN_ATTEMPT_LIMIT: 3,
  GLOBAL_ROOM_CODE: 'CHATNOW-ALL',
  ADMIN_ROOMS: ['ADMIN-CHAT'],
  MAX_MESSAGE_LENGTH: 5000,
  USERNAME_MIN_LENGTH: 3,
  USERNAME_MAX_LENGTH: 20,
  PASSWORD_MIN_LENGTH: 8,
  EMOJI_WHITELIST: ['👍', '❤️', '😂', '😮', '😢', '🙏', '🔥', '🎉', '💯', '⭐']
};
